import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { renderToBuffer } from "@react-pdf/renderer";

interface PropertyPerformanceRow {
  listing_name: string;
  listing_status: string;
  revenue: number;
  revenue_prior: number;
  revenue_delta: number | null;
  nights_booked: number;
  occupancy: number;
  occupancy_prior: number;
  occupancy_delta: number | null;
  adr: number;
  bookings_count: number;
}

interface ReportData {
  properties: PropertyPerformanceRow[];
  startDate: string;
  endDate: string;
  hostName: string;
}

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 9,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
    color: "#111827",
  },
  subtitle: {
    fontSize: 10,
    color: "#6B7280",
    marginBottom: 10,
  },
  table: {
    width: "100%",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#10B981",
    padding: 6,
    fontWeight: "bold",
    color: "#FFFFFF",
    fontSize: 8,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    padding: 6,
    fontSize: 8,
  },
  tableRowAlt: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
    padding: 6,
    fontSize: 8,
  },
  col1: { width: "18%", paddingRight: 4 },
  col2: { width: "8%", paddingRight: 4 },
  col3: { width: "11%", textAlign: "right", paddingRight: 4 },
  col4: { width: "10%", textAlign: "right", paddingRight: 4 },
  col5: { width: "9%", textAlign: "right", paddingRight: 4 },
  col6: { width: "8%", textAlign: "right", paddingRight: 4 },
  col7: { width: "10%", textAlign: "right", paddingRight: 4 },
  col8: { width: "10%", textAlign: "right", paddingRight: 4 },
  col9: { width: "8%", textAlign: "right", paddingRight: 4 },
  col10: { width: "8%", textAlign: "right", paddingRight: 4 },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 30,
    right: 30,
    textAlign: "center",
    fontSize: 8,
    color: "#9CA3AF",
  },
});

function PropertyPerformancePDF({ data }: { data: ReportData }) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Property Performance Report</Text>
          <Text style={styles.subtitle}>
            {data.hostName} · {data.startDate} to {data.endDate}
          </Text>
        </View>

        {/* Table */}
        <View style={styles.table}>
          {/* Table Header */}
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Property</Text>
            <Text style={styles.col2}>Status</Text>
            <Text style={styles.col3}>Revenue</Text>
            <Text style={styles.col4}>Rev Prior</Text>
            <Text style={styles.col5}>Rev Δ %</Text>
            <Text style={styles.col6}>Nights</Text>
            <Text style={styles.col7}>Occ %</Text>
            <Text style={styles.col8}>Occ Prior</Text>
            <Text style={styles.col9}>Occ Δ</Text>
            <Text style={styles.col10}>ADR</Text>
          </View>

          {/* Table Rows */}
          {data.properties.map((property, index) => {
            const rowStyle = index % 2 === 0 ? styles.tableRow : styles.tableRowAlt;

            return (
              <View key={index} style={rowStyle}>
                <Text style={styles.col1}>{property.listing_name}</Text>
                <Text style={styles.col2}>{property.listing_status}</Text>
                <Text style={styles.col3}>R {formatNumber(property.revenue)}</Text>
                <Text style={styles.col4}>R {formatNumber(property.revenue_prior)}</Text>
                <Text style={styles.col5}>
                  {property.revenue_delta !== null
                    ? `${property.revenue_delta.toFixed(1)}%`
                    : "N/A"}
                </Text>
                <Text style={styles.col6}>{property.nights_booked}</Text>
                <Text style={styles.col7}>{property.occupancy.toFixed(1)}%</Text>
                <Text style={styles.col8}>{property.occupancy_prior.toFixed(1)}%</Text>
                <Text style={styles.col9}>
                  {property.occupancy_delta !== null
                    ? `${property.occupancy_delta.toFixed(1)}pp`
                    : "N/A"}
                </Text>
                <Text style={styles.col10}>R {formatNumber(property.adr)}</Text>
              </View>
            );
          })}
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by Vilo Analytics on {new Date().toLocaleDateString("en-ZA")} · {data.properties.length} properties
        </Text>
      </Page>
    </Document>
  );
}

export async function generatePDF(data: ReportData): Promise<Buffer> {
  const doc = <PropertyPerformancePDF data={data} />;
  const buffer = await renderToBuffer(doc);
  return buffer;
}

// Helper: Format number with spaces for thousands
function formatNumber(value: number): string {
  return value
    .toFixed(0)
    .replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}
