// Placeholder — will be regenerated by:
//   supabase gen types typescript --local > packages/types/database.types.ts
// once DB migrations exist (see PHASE_PLAN.md Phase 0 — Database).
export type Database = Record<string, never>;
