"use server";

import { redirect } from "next/navigation";

import { createServerClient } from "@/lib/supabase/server";
import { assertFullHost } from "@/lib/host/current";
import { assertWithinTotalCap } from "@/lib/products/featureGate";

import { newListingSchema, type NewListingInput } from "./schemas";

export type CreateListingResult = { ok: true } | { ok: false; error: string };

export async function createListingAction(
  input: NewListingInput,
): Promise<CreateListingResult> {
  const parsed = newListingSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "Please check the form and try again." };
  }
  const d = parsed.data;

  // Full-host-only: a quotes-only / platform-blocked account is rejected
  // server-side (the sidebar lock is only UX).
  const h = await assertFullHost();
  if (!h.ok) return h;

  const supabase = createServerClient();

  // Enforce the account's listings cap (listings_limit). RLS scopes the count to
  // this host's own non-deleted listings.
  const { count } = await supabase
    .from("properties")
    .select("id", { count: "exact", head: true })
    .eq("host_id", h.hostId)
    .is("deleted_at", null);
  const cap = await assertWithinTotalCap(
    supabase,
    h.hostId,
    "listings_limit",
    count ?? 0,
    "listing",
  );
  if (!cap.ok) return cap;

  // host_manage_own_listings RLS lets the user-bound client insert.
  const { data: listing, error } = await supabase
    .from("properties")
    .insert({
      host_id: h.hostId,
      property_type: "accommodation",
      category_id: d.category_id,
      accommodation_type: d.accommodation_type ?? null,
      name: d.name,
      // is_published defaults to false; slug auto-generated by trigger.
    })
    .select("id")
    .single();
  if (error || !listing) {
    return { ok: false, error: "Could not create the listing. Try again." };
  }

  redirect(`/dashboard/properties/${listing.id}/edit`);
}
