"use server";

import { redirect } from "next/navigation";

import { createServerClient } from "@/lib/supabase/server";
import { assertFullHost } from "@/lib/host/current";

import { newListingSchema, type NewListingInput } from "./schemas";

export type CreateListingResult = { ok: true } | { ok: false; error: string };

export async function createListingAction(
  input: NewListingInput,
): Promise<CreateListingResult> {
  const parsed = newListingSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "Please check the form and try again." };
  }
  const d = parsed.data;

  // Full-host-only: a quotes-only / platform-blocked account is rejected
  // server-side (the sidebar lock is only UX).
  const h = await assertFullHost();
  if (!h.ok) return h;

  const supabase = createServerClient();

  // host_manage_own_listings RLS lets the user-bound client insert.
  const { data: listing, error } = await supabase
    .from("properties")
    .insert({
      host_id: h.hostId,
      property_type: "accommodation",
      category_id: d.category_id,
      accommodation_type: d.accommodation_type ?? null,
      name: d.name,
      // is_published defaults to false; slug auto-generated by trigger.
    })
    .select("id")
    .single();
  if (error || !listing) {
    return { ok: false, error: "Could not create the listing. Try again." };
  }

  redirect(`/dashboard/properties/${listing.id}/edit`);
}
