"use server";

import { redirect } from "next/navigation";

import { createServerClient } from "@/lib/supabase/server";

import { onboardingSchema, type OnboardingInput } from "./schemas";

export type FinalizeResult = { ok: true } | { ok: false; error: string };

export async function finalizeOnboardingAction(
  input: OnboardingInput,
): Promise<FinalizeResult> {
  const parsed = onboardingSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "Please check the form and try again." };
  }
  const d = parsed.data;

  // Free is the only plan that completes the wizard for now. Paid plans land
  // when subscription billing ships in Phase 3.
  if (d.plan !== "free") {
    return {
      ok: false,
      error: "Paid plans land after launch. Start free, upgrade later.",
    };
  }

  const supabase = createServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { ok: false, error: "Sign in again to finish onboarding." };
  }

  // Bail if onboarding already ran (e.g. double-submit, duplicate tab).
  const { data: existingHost } = await supabase
    .from("hosts")
    .select("id")
    .eq("user_id", user.id)
    .maybeSingle();
  if (existingHost) {
    redirect("/dashboard");
  }

  // 1. Profile details.
  const { error: profileErr } = await supabase
    .from("user_profiles")
    .update({
      full_name: d.full_name,
      phone: d.phone && d.phone.length > 0 ? d.phone : null,
    })
    .eq("id", user.id);
  if (profileErr) {
    return { ok: false, error: "Could not save your details. Try again." };
  }

  // 2. Host row — handle auto-generated by trigger_host_handle from display_name.
  const { data: host, error: hostErr } = await supabase
    .from("hosts")
    .insert({
      user_id: user.id,
      display_name: d.display_name,
    })
    .select("id, handle")
    .single();
  if (hostErr || !host) {
    return {
      ok: false,
      error: "Could not create your host profile. Try again.",
    };
  }

  // 3. First listing (draft — is_published defaults to false).
  const { error: listingErr } = await supabase.from("listings").insert({
    host_id: host.id,
    listing_type: d.listing_type,
    accommodation_type:
      d.listing_type === "accommodation"
        ? (d.accommodation_type ?? null)
        : null,
    experience_type:
      d.listing_type === "experience" ? (d.experience_type ?? null) : null,
    name: d.name,
    description:
      d.description && d.description.length > 0 ? d.description : null,
  });
  if (listingErr) {
    // Best-effort cleanup so the user can retry the wizard.
    await supabase.from("hosts").delete().eq("id", host.id);
    return {
      ok: false,
      error: "Could not save your first listing. Try again.",
    };
  }

  // 4. Subscription — Free tier; status active, no trial countdown.
  const { error: subErr } = await supabase.from("subscriptions").insert({
    host_id: host.id,
    plan: "free",
    status: "active",
  });
  if (subErr) {
    // Non-blocking: host + listing are valid, billing can be backfilled.
    // Server-side error capture lands when Sentry is wired (deferred).
  }

  redirect("/dashboard?welcome=1");
}
