"use server";

import { redirect } from "next/navigation";

import { createAdminClient } from "@/lib/supabase/admin";
import { createServerClient } from "@/lib/supabase/server";

import {
  accountSchema,
  finalizeOnboardingSchema,
  type AccountInput,
  type FinalizeOnboardingInput,
} from "./schemas";

export type ActionResult<T = undefined> =
  | { ok: true; data?: T }
  | { ok: false; error: string };

// ─── Step 1: create the auth user + sign them in ─────────────────
//
// Uses the admin client to create with email_confirm = true so the founder
// can smoke-test the whole onboarding without needing to click a verification
// email. When real-user email verification is required later, flip this to
// regular `supabase.auth.signUp` and require the user to come back via the
// confirm link.

export async function createAccountAction(
  input: AccountInput,
): Promise<ActionResult> {
  const parsed = accountSchema.safeParse(input);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    return { ok: false, error: first?.message ?? "Some fields look wrong." };
  }
  const d = parsed.data;

  const admin = createAdminClient();

  // Create user with email pre-confirmed.
  const { error: createErr } = await admin.auth.admin.createUser({
    email: d.email,
    password: d.password,
    email_confirm: true,
    user_metadata: { full_name: d.full_name },
  });
  if (createErr) {
    if (
      createErr.message.toLowerCase().includes("already") ||
      createErr.message.toLowerCase().includes("registered")
    ) {
      return {
        ok: false,
        error:
          "An account with this email already exists. Sign in instead, or use a different email.",
      };
    }
    return { ok: false, error: "Could not create your account. Try again." };
  }

  // Sign them in immediately so the wizard can continue under their session.
  const supabase = createServerClient();
  const { error: signInErr } = await supabase.auth.signInWithPassword({
    email: d.email,
    password: d.password,
  });
  if (signInErr) {
    return {
      ok: false,
      error: "Account was created but sign-in failed. Try signing in manually.",
    };
  }

  return { ok: true };
}

// ─── Final step: create profile + host + listing + free subscription ─

export async function finalizeOnboardingAction(
  input: FinalizeOnboardingInput,
): Promise<ActionResult> {
  const parsed = finalizeOnboardingSchema.safeParse(input);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    return {
      ok: false,
      error: first?.message ?? "Please check the form and try again.",
    };
  }
  const d = parsed.data;

  const supabase = createServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return {
      ok: false,
      error: "Your session expired — sign back in to finish onboarding.",
    };
  }

  // Bail if onboarding already ran (e.g. double-submit, duplicate tab).
  const { data: existingHost } = await supabase
    .from("hosts")
    .select("id")
    .eq("user_id", user.id)
    .maybeSingle();
  if (existingHost) {
    redirect("/dashboard?welcome=1");
  }

  // 1. Profile details.
  const { error: profileErr } = await supabase
    .from("user_profiles")
    .update({
      full_name: d.full_name,
      phone: d.phone && d.phone.length > 0 ? d.phone : null,
      role: "host",
    })
    .eq("id", user.id);
  if (profileErr) {
    return { ok: false, error: "Could not save your details. Try again." };
  }

  // 2. Host row — handle auto-generated by trigger_host_handle from
  //    display_name. Display name defaults to full_name for now.
  const { data: host, error: hostErr } = await supabase
    .from("hosts")
    .insert({
      user_id: user.id,
      display_name: d.full_name,
      bio: d.bio && d.bio.length > 0 ? d.bio : null,
      languages_spoken: d.languages,
    })
    .select("id, handle")
    .single();
  if (hostErr || !host) {
    return {
      ok: false,
      error: "Could not create your host profile. Try again.",
    };
  }

  // 3. First listing — populated from the wizard's listing step.
  const listingType: "accommodation" | "experience" =
    d.offering === "experiences" ? "experience" : "accommodation";
  // listing_kind from the form mostly mirrors offering, but respect explicit
  // override (e.g. offering=both with kind=experience).
  const finalKind = d.listing_kind ?? listingType;

  // Seed a DRAFT listing — host fills in capacity / pricing / duration /
  // photos / amenities via the listing editor before publishing.
  // is_published defaults to false, base_price / max_guests / duration_minutes
  // stay NULL until the host completes the editor.
  const { error: listingErr } = await supabase.from("listings").insert({
    host_id: host.id,
    listing_type: finalKind,
    accommodation_type:
      finalKind === "accommodation" ? (d.accommodation_type ?? null) : null,
    experience_type:
      finalKind === "experience" ? (d.experience_type ?? null) : null,
    name: d.listing_name,
    city: d.city,
    province: d.region,
  });
  if (listingErr) {
    // Best-effort cleanup so the user can retry the wizard.
    await supabase.from("hosts").delete().eq("id", host.id);
    return {
      ok: false,
      error: "Could not save your first listing. Try again.",
    };
  }

  // 4. Subscription — FREE for now regardless of what they picked. Payment
  //    + plan upgrade flow lands later.
  const { error: subErr } = await supabase.from("subscriptions").insert({
    host_id: host.id,
    plan: "free",
    status: "active",
  });
  if (subErr) {
    // Non-blocking — billing can be backfilled. The TEMP free-unlock
    // migration also means every feature works without a paid sub.
  }

  redirect("/dashboard?welcome=1");
}
