// Curated free-icon catalogue (Lucide — ISC-licensed, already a dependency).
//
// The SINGLE source shared by the public renderer (`SiteIcon`) and the builder's
// `IconPicker`. Icons are stored on a node as `lucide:<key>` (e.g. `lucide:waves`);
// anything else is an emoji glyph or an uploaded image URL/path. We import a
// curated ~110-icon set (not all 1500) so the public bundle stays lean — the same
// principle as Elementor shipping a searchable library rather than every glyph.
import {
  Waves,
  Wifi,
  Coffee,
  Utensils,
  UtensilsCrossed,
  Wine,
  Beer,
  Martini,
  CupSoda,
  GlassWater,
  Croissant,
  Cake,
  IceCream,
  Pizza,
  Salad,
  Soup,
  Grape,
  Apple,
  Carrot,
  Egg,
  Milk,
  Bath,
  ShowerHead,
  Bed,
  BedDouble,
  DoorOpen,
  Key,
  Home,
  Building,
  Building2,
  Hotel,
  Tent,
  Car,
  Bus,
  Bike,
  Plane,
  TrainFront,
  Ship,
  Sailboat,
  Anchor,
  Fish,
  MapPin,
  Map,
  Navigation,
  Compass,
  Footprints,
  Mountain,
  MountainSnow,
  TreePine,
  Trees,
  Leaf,
  Sprout,
  Flower,
  Flower2,
  Sun,
  Sunrise,
  Sunset,
  Moon,
  Cloud,
  CloudSun,
  Snowflake,
  Wind,
  Umbrella,
  Thermometer,
  Flame,
  Sparkles,
  Sparkle,
  Star,
  Heart,
  Award,
  Trophy,
  Crown,
  Gem,
  Gift,
  Dog,
  Cat,
  Bird,
  Dumbbell,
  Camera,
  Music,
  Guitar,
  Tv,
  Speaker,
  Gamepad2,
  BookOpen,
  Newspaper,
  Palette,
  Brush,
  Scissors,
  Zap,
  WashingMachine,
  ShoppingBag,
  ShoppingCart,
  CreditCard,
  Wallet,
  Tag,
  Ticket,
  BadgePercent,
  Calendar,
  CalendarCheck,
  Clock,
  Phone,
  Mail,
  MessageCircle,
  Send,
  Share2,
  ThumbsUp,
  Smile,
  Users,
  User,
  UserCheck,
  ShieldCheck,
  Lock,
  Check,
  CircleCheck,
  Info,
  CircleHelp,
  Settings,
  Search,
  type LucideIcon,
} from "lucide-react";

/** Curated icon set — keyed by the Lucide canonical (kebab-case) name. */
export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  waves: Waves,
  wifi: Wifi,
  coffee: Coffee,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  wine: Wine,
  beer: Beer,
  martini: Martini,
  "cup-soda": CupSoda,
  "glass-water": GlassWater,
  croissant: Croissant,
  cake: Cake,
  "ice-cream": IceCream,
  pizza: Pizza,
  salad: Salad,
  soup: Soup,
  grape: Grape,
  apple: Apple,
  carrot: Carrot,
  egg: Egg,
  milk: Milk,
  bath: Bath,
  "shower-head": ShowerHead,
  bed: Bed,
  "bed-double": BedDouble,
  "door-open": DoorOpen,
  key: Key,
  home: Home,
  building: Building,
  "building-2": Building2,
  hotel: Hotel,
  tent: Tent,
  car: Car,
  bus: Bus,
  bike: Bike,
  plane: Plane,
  "train-front": TrainFront,
  ship: Ship,
  sailboat: Sailboat,
  anchor: Anchor,
  fish: Fish,
  "map-pin": MapPin,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  footprints: Footprints,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  "tree-pine": TreePine,
  trees: Trees,
  leaf: Leaf,
  sprout: Sprout,
  flower: Flower,
  "flower-2": Flower2,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  moon: Moon,
  cloud: Cloud,
  "cloud-sun": CloudSun,
  snowflake: Snowflake,
  wind: Wind,
  umbrella: Umbrella,
  thermometer: Thermometer,
  flame: Flame,
  sparkles: Sparkles,
  sparkle: Sparkle,
  star: Star,
  heart: Heart,
  award: Award,
  trophy: Trophy,
  crown: Crown,
  gem: Gem,
  gift: Gift,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  dumbbell: Dumbbell,
  camera: Camera,
  music: Music,
  guitar: Guitar,
  tv: Tv,
  speaker: Speaker,
  "gamepad-2": Gamepad2,
  "book-open": BookOpen,
  newspaper: Newspaper,
  palette: Palette,
  brush: Brush,
  scissors: Scissors,
  zap: Zap,
  "washing-machine": WashingMachine,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  wallet: Wallet,
  tag: Tag,
  ticket: Ticket,
  "badge-percent": BadgePercent,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  clock: Clock,
  phone: Phone,
  mail: Mail,
  "message-circle": MessageCircle,
  send: Send,
  "share-2": Share2,
  "thumbs-up": ThumbsUp,
  smile: Smile,
  users: Users,
  user: User,
  "user-check": UserCheck,
  "shield-check": ShieldCheck,
  lock: Lock,
  check: Check,
  "circle-check": CircleCheck,
  info: Info,
  "circle-help": CircleHelp,
  settings: Settings,
  search: Search,
};

/** Ordered list of catalogue keys (for the picker grid). */
export const LUCIDE_ICON_NAMES = Object.keys(LUCIDE_ICONS);

/** The `lucide:` prefix marks an icon value as a catalogue pick. */
export const LUCIDE_PREFIX = "lucide:";

/** True when an icon value references the Lucide catalogue (`lucide:<name>`). */
export function isLucideIcon(v?: string | null): boolean {
  return !!v && v.startsWith(LUCIDE_PREFIX);
}

/** Resolve a `lucide:<name>` value to its component, or null when unknown. */
export function lucideIconFor(value?: string | null): LucideIcon | null {
  if (!isLucideIcon(value)) return null;
  return LUCIDE_ICONS[value!.slice(LUCIDE_PREFIX.length)] ?? null;
}
