"use server";

import { assertFullHost } from "@/lib/host/current";
import { assertWithinTotalCap } from "@/lib/products/featureGate";
import { createServerClient } from "@/lib/supabase/server";

import {
  newListingSchema,
  type NewListingInput,
} from "../properties/new/schemas";

export type CreateSetupListingResult =
  | { ok: true; listingId: string }
  | { ok: false; error: string };

// Create the host's FIRST listing from inside the finish-setup wizard.
//
// Mirrors createListingAction (dashboard/properties/new/actions.ts) — same
// assertFullHost + listings-cap guards and the same `properties` insert — but
// returns the new id instead of redirecting into the tabbed editor. The setup
// wizard has no listing at all for a host who came through the leaner signup
// (signup no longer seeds one), so this lets the wizard's opening step create
// the draft in place and then refresh into the full wizard. is_published stays
// false and the slug is trigger-generated, exactly as in the standard create.
export async function createSetupListingAction(
  input: NewListingInput,
): Promise<CreateSetupListingResult> {
  const parsed = newListingSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "Please check the form and try again." };
  }
  const d = parsed.data;

  // Full-host-only (a quotes-only / platform-blocked account is rejected
  // server-side; the sidebar lock is only UX).
  const h = await assertFullHost();
  if (!h.ok) return h;

  const supabase = createServerClient();

  // Enforce the account's listings cap (listings_limit). RLS scopes the count
  // to this host's own non-deleted listings.
  const { count } = await supabase
    .from("properties")
    .select("id", { count: "exact", head: true })
    .eq("host_id", h.hostId)
    .is("deleted_at", null);
  const cap = await assertWithinTotalCap(
    supabase,
    h.hostId,
    "listings_limit",
    count ?? 0,
    "listing",
  );
  if (!cap.ok) return cap;

  // host_manage_own_listings RLS lets the user-bound client insert.
  const { data: listing, error } = await supabase
    .from("properties")
    .insert({
      host_id: h.hostId,
      property_type: "accommodation",
      category_id: d.category_id,
      accommodation_type: d.accommodation_type ?? null,
      name: d.name,
      // is_published defaults to false; slug auto-generated by trigger.
    })
    .select("id")
    .single();
  if (error || !listing) {
    return { ok: false, error: "Could not create your listing. Try again." };
  }

  return { ok: true, listingId: listing.id as string };
}
