"use server";

import { headers } from "next/headers";

import { bindAffiliateReferral } from "@/lib/affiliate/attribution";
import { getConsentVersion } from "@/lib/auth/consent";
import { isBreachedPassword } from "@/lib/auth/password";
import { checkSignupRateLimit } from "@/lib/auth/rateLimit";
import {
  sendSignupCollisionEmail,
  sendVerificationEmail,
} from "@/lib/auth/verifyEmail";
import { isHoneypotTripped } from "@/lib/security/honeypot";
import { clientIpFromHeaders, verifyTurnstile } from "@/lib/security/turnstile";
import { createAdminClient } from "@/lib/supabase/admin";
import { createServerClient } from "@/lib/supabase/server";
import { combineName } from "@/lib/profile/name";

import { accountSchema, type AccountInput } from "../host/schemas";

export type ActionResult = { ok: true } | { ok: false; error: string };

// ─── Self-serve QUOTE-ONLY signup ─────────────────────────────────────
// Creates a standalone "Wielo Quotes" account: an external quoter who responds
// to Looking-For requests but does NOT run listings/bookings. Same hardened
// account creation as the host signup (rate limit, Turnstile, HIBP, soft email
// verification), but the host row is flagged account_kind='quote_only' up front,
// so the user lands directly in the scoped quotes-only shell. They pick up
// credits from the Credits page (buy a pack or subscribe to Wielo Quotes).
export async function createQuotesAccountAction(
  input: AccountInput,
  captchaToken?: string | null,
  honeypot?: string | null,
): Promise<ActionResult> {
  // Honeypot — a filled decoy field means a bot; reject quietly (see
  // lib/security/honeypot.ts). Free, always-on — Turnstile is inert unkeyed.
  if (isHoneypotTripped(honeypot)) {
    return { ok: false, error: "Could not create your account. Try again." };
  }

  const parsed = accountSchema.safeParse(input);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    return { ok: false, error: first?.message ?? "Some fields look wrong." };
  }
  const d = parsed.data;
  const full_name = combineName(d.first_name, d.surname);

  const hdrs = headers();
  const origin = hdrs.get("origin") ?? "";
  const ip = clientIpFromHeaders(hdrs);

  const limit = await checkSignupRateLimit(ip);
  if (!limit.ok) {
    return {
      ok: false,
      error: "Too many signups from this network. Please try again later.",
    };
  }

  const captcha = await verifyTurnstile(captchaToken, ip);
  if (!captcha.ok) {
    return {
      ok: false,
      error: "Couldn't verify you're human. Refresh and try again.",
    };
  }

  if (await isBreachedPassword(d.password)) {
    return {
      ok: false,
      error:
        "That password has appeared in a data breach. Please choose a different one.",
    };
  }

  const admin = createAdminClient();

  const { data: created, error: createErr } = await admin.auth.admin.createUser(
    {
      email: d.email,
      password: d.password,
      email_confirm: true,
      user_metadata: { full_name },
    },
  );
  if (createErr || !created?.user) {
    const msg = createErr?.message?.toLowerCase() ?? "";
    if (
      msg.includes("already") ||
      msg.includes("registered") ||
      msg.includes("exists")
    ) {
      // A passwordless lead gets a claim link, not a "just sign in" notice they
      // have no password to act on (BUSINESS_PRINCIPLES #1 rule 3).
      const sent = await sendSignupCollisionEmail({ email: d.email, origin });
      return {
        ok: false,
        error:
          sent === "claim"
            ? "You already have an account with this email — check your inbox for a link to set your password."
            : "We couldn't complete your signup. If you already have an account, sign in or reset your password.",
      };
    }
    return { ok: false, error: "Could not create your account. Try again." };
  }
  const newUserId = created.user.id;

  // Provision the quote-only host substrate. If it fails, roll back the auth user
  // so we never leave a half-provisioned orphan (mirrors createUserAction).
  try {
    const { error: profileErr } = await admin
      .from("user_profiles")
      .update({
        full_name,
        role: "host",
        is_lead: false,
        terms_accepted_at: new Date().toISOString(),
        terms_version: await getConsentVersion(),
      })
      .eq("id", newUserId);
    if (profileErr) throw new Error(profileErr.message);

    // handle is auto-generated by the trigger_host_handle trigger from
    // display_name; account_kind='quote_only' puts them in the scoped shell.
    const { error: hostErr } = await admin.from("hosts").insert({
      user_id: newUserId,
      display_name: full_name,
      account_kind: "quote_only",
    });
    if (hostErr) throw new Error(hostErr.message);
  } catch {
    await admin.auth.admin.deleteUser(newUserId).catch(() => {});
    return { ok: false, error: "Could not set up your account. Try again." };
  }

  // Sign them in so they land in the dashboard (scoped shell).
  const supabase = createServerClient();
  const { error: signInErr } = await supabase.auth.signInWithPassword({
    email: d.email,
    password: d.password,
  });
  if (signInErr) {
    return {
      ok: false,
      error: "Account was created but sign-in failed. Try signing in manually.",
    };
  }

  await sendVerificationEmail({
    userId: newUserId,
    email: d.email,
    origin,
    firstName: d.first_name,
  });
  await bindAffiliateReferral(newUserId);

  return { ok: true };
}
