import "server-only";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import { websiteAssetUrl } from "@/lib/website/assets";

import { SITE_PRESETS, DEFAULT_PRESET, type SitePreset } from "./themes";

/**
 * A cookieless Supabase client for reading the PUBLIC theme catalogue.
 *
 * `site_themes` has a public read RLS policy (`select using (is_active and
 * deleted_at is null)`), so the catalogue can be read with the anon key — no
 * service role needed. Prefer the service-role key when present (bypasses RLS,
 * e.g. to resolve a base by slug regardless of is_active), but fall back to the
 * always-present anon key. This is what stops the picker silently collapsing to
 * a single preset when SUPABASE_SERVICE_ROLE_KEY isn't wired into a given
 * deployment environment (the previous `createAdminClient()` THREW in that case,
 * and every caller's try/catch degraded to the one-theme fallback).
 */
function themesReadClient(): SupabaseClient | null {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) return null;
  return createClient(url, key, {
    auth: { autoRefreshToken: false, persistSession: false },
    // Read the catalogue fresh every request. Supabase-js reads through `fetch`,
    // which the Next.js/Vercel Data Cache would otherwise persist — including a
    // stale empty result from before the anon grant / service key was in place,
    // which no redeploy would clear. `no-store` keeps the picker always current.
    global: {
      fetch: (input: RequestInfo | URL, init?: RequestInit) =>
        fetch(input, { ...init, cache: "no-store" }),
    },
  });
}

/** One selectable theme for the Brand Studio gallery / preset cards. */
export type ThemeOption = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  previewUrl: string | null;
  base: SitePreset;
  isPremium: boolean;
  price: number | null;
};

type ThemeRow = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  preview_image_path: string | null;
  base: SitePreset;
  is_premium: boolean | null;
  price: number | null;
};

/** The default preset as the sole theme — used as a safety fallback when the
 * site_themes catalogue is empty/unavailable. Only the default theme is offered;
 * other themes were removed from the system. */
function presetThemes(): ThemeOption[] {
  const slug = DEFAULT_PRESET;
  return [
    {
      id: `preset:${slug}`,
      slug,
      name: SITE_PRESETS[slug].label,
      description: null,
      previewUrl: null,
      base: SITE_PRESETS[slug],
      isPremium: false,
      price: null,
    },
  ];
}

/**
 * Load the active theme catalogue (site_themes), ordered. Falls back to the
 * built-in presets when the table doesn't exist yet, is empty, or errors — so
 * the studio works whether or not the migration has been applied. Uses the
 * admin client (catalogue is platform-managed, read here only).
 *
 * NOTE: queried through an untyped client cast because `site_themes` isn't in
 * the generated DB types in this lane (types are regenerated by the
 * consolidation lane after the migration is applied).
 */
export async function loadActiveThemes(): Promise<ThemeOption[]> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  // Try BOTH keys, anon first: site_themes is public-read, so the anon key is the
  // intended path. A key that is present but WRONG (e.g. a new `sb_secret_…` value
  // where the legacy `eyJ…` JWT is expected) fails on its own attempt and we move
  // to the next — instead of the whole loader collapsing to a single preset the
  // moment SUPABASE_SERVICE_ROLE_KEY is set to something the client rejects.
  const attempts: Array<{ label: string; key: string | undefined }> = [
    { label: "anon", key: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY },
    { label: "service", key: process.env.SUPABASE_SERVICE_ROLE_KEY },
  ];
  if (!url) {
    console.warn("[themes-load] NEXT_PUBLIC_SUPABASE_URL missing → preset");
    return presetThemes();
  }

  for (const { label, key } of attempts) {
    if (!key) continue;
    try {
      const sb = createClient(url, key, {
        auth: { autoRefreshToken: false, persistSession: false },
        global: {
          fetch: (input: RequestInfo | URL, init?: RequestInit) =>
            fetch(input, { ...init, cache: "no-store" }),
        },
      });
      const { data, error } = await sb
        .from("site_themes")
        .select(
          "id, slug, name, description, preview_image_path, base, is_premium, price",
        )
        .eq("is_active", true)
        .is("deleted_at", null)
        .order("sort_order", { ascending: true });

      const rows = (data ?? []) as ThemeRow[];
      if (error) {
        console.warn(
          `[themes-load] ${label} key error: ${error.code ?? ""} ${error.message}`,
        );
        continue;
      }
      if (rows.length === 0) {
        console.warn(`[themes-load] ${label} key returned 0 rows`);
        continue;
      }
      console.info(`[themes-load] ${label} key → ${rows.length} themes`);
      return rows.map((r) => ({
        id: r.id,
        slug: r.slug,
        name: r.name,
        description: r.description ?? null,
        previewUrl: websiteAssetUrl(r.preview_image_path),
        base: (r.base ?? {}) as SitePreset,
        isPremium: !!r.is_premium,
        price: r.price ?? null,
      }));
    } catch (e) {
      console.warn(
        `[themes-load] ${label} key threw: ${(e as Error)?.message ?? e}`,
      );
    }
  }

  console.warn("[themes-load] all attempts empty/failed → preset fallback");
  return presetThemes();
}

/** One page template carried by a theme (seeds website_pages on apply). */
export type ThemePageTemplate = {
  kind: string;
  slug: string;
  title: string;
  nav_label: string;
  nav_order: number;
  show_in_nav: boolean;
  sections: unknown[];
};

export type ThemeBundle = {
  slug: string;
  base: SitePreset;
  pageTemplates: ThemePageTemplate[];
};

/** Load a catalogue theme (by uuid) with its base + page templates — for the
 * apply-theme flow. Returns null if not found / catalogue unavailable. */
export async function getThemeBundle(
  themeId: string,
): Promise<ThemeBundle | null> {
  try {
    const sb = themesReadClient();
    if (!sb) return null;
    const { data, error } = await sb
      .from("site_themes")
      .select("slug, base, page_templates")
      .eq("id", themeId)
      .eq("is_active", true)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as {
      slug: string;
      base: SitePreset;
      page_templates: ThemePageTemplate[] | null;
    } | null;
    if (error || !row) return null;
    return {
      slug: row.slug,
      base: row.base,
      pageTemplates: Array.isArray(row.page_templates)
        ? row.page_templates
        : [],
    };
  } catch {
    return null;
  }
}

/**
 * Load the default theme (is_default = true) with its base + page templates.
 * Used when creating a new website to apply the default theme automatically.
 * Falls back to the hardcoded "warm" preset if the DB is unavailable.
 */
export async function loadDefaultTheme(): Promise<ThemeBundle | null> {
  try {
    const sb = themesReadClient();
    if (!sb) return null;
    const { data, error } = await sb
      .from("site_themes")
      .select("slug, base, page_templates")
      .eq("is_default", true)
      .eq("is_active", true)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as {
      slug: string;
      base: SitePreset;
      page_templates: ThemePageTemplate[] | null;
    } | null;
    if (error || !row) return null;
    return {
      slug: row.slug,
      base: row.base,
      pageTemplates: Array.isArray(row.page_templates)
        ? row.page_templates
        : [],
    };
  } catch {
    return null;
  }
}

/**
 * Resolve a theme's designed page templates by slug — the demo composition the
 * theme ships (home/about/rooms/contact/blog/...). Used by the theme-gallery
 * full-site PREVIEW so "preview" shows the theme's actual design, not the host's
 * own pages tinted with the theme. Returns [] if the catalogue is unavailable.
 */
export async function resolveThemePageTemplates(
  slug: string,
): Promise<ThemePageTemplate[]> {
  try {
    const sb = themesReadClient();
    if (!sb) return [];
    const { data, error } = await sb
      .from("site_themes")
      .select("page_templates")
      .eq("slug", slug)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as { page_templates?: ThemePageTemplate[] | null } | null;
    if (!error && Array.isArray(row?.page_templates)) return row.page_templates;
  } catch {
    // fall through
  }
  return [];
}

/**
 * Resolve a theme's visual base by slug — the authoritative source for what gets
 * stored on save (so we never trust a client-sent base). Falls back to the
 * built-in preset of the same slug when the catalogue is unavailable.
 */
export async function resolveThemeBase(slug: string): Promise<SitePreset> {
  try {
    const sb = themesReadClient();
    if (sb) {
      const { data, error } = await sb
        .from("site_themes")
        .select("base")
        .eq("slug", slug)
        .is("deleted_at", null)
        .maybeSingle();
      const row = data as { base?: SitePreset } | null;
      if (!error && row?.base?.palette) return row.base;
    }
  } catch {
    // fall through to preset fallback
  }
  if (slug in SITE_PRESETS) {
    return SITE_PRESETS[slug as keyof typeof SITE_PRESETS];
  }
  return SITE_PRESETS.warm;
}
