import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import { createAdminClient } from "@/lib/supabase/admin";
import { websiteAssetUrl } from "@/lib/website/assets";

import { SITE_PRESETS, SITE_PRESET_KEYS, type SitePreset } from "./themes";

/** One selectable theme for the Brand Studio gallery / preset cards. */
export type ThemeOption = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  previewUrl: string | null;
  base: SitePreset;
  isPremium: boolean;
  price: number | null;
};

type ThemeRow = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  preview_image_path: string | null;
  base: SitePreset;
  is_premium: boolean | null;
  price: number | null;
};

/** The 6 built-in presets as themes — used until the site_themes table is
 * applied (and as a safety fallback if the catalogue is empty/unavailable). */
function presetThemes(): ThemeOption[] {
  return SITE_PRESET_KEYS.map((slug) => ({
    id: `preset:${slug}`,
    slug,
    name: SITE_PRESETS[slug].label,
    description: null,
    previewUrl: null,
    base: SITE_PRESETS[slug],
    isPremium: false,
    price: null,
  }));
}

/**
 * Load the active theme catalogue (site_themes), ordered. Falls back to the
 * built-in presets when the table doesn't exist yet, is empty, or errors — so
 * the studio works whether or not the migration has been applied. Uses the
 * admin client (catalogue is platform-managed, read here only).
 *
 * NOTE: queried through an untyped client cast because `site_themes` isn't in
 * the generated DB types in this lane (types are regenerated by the
 * consolidation lane after the migration is applied).
 */
export async function loadActiveThemes(): Promise<ThemeOption[]> {
  try {
    const sb = createAdminClient() as unknown as SupabaseClient;
    const { data, error } = await sb
      .from("site_themes")
      .select(
        "id, slug, name, description, preview_image_path, base, is_premium, price",
      )
      .eq("is_active", true)
      .is("deleted_at", null)
      .order("sort_order", { ascending: true });

    const rows = (data ?? []) as ThemeRow[];
    if (error || rows.length === 0) return presetThemes();

    return rows.map((r) => ({
      id: r.id,
      slug: r.slug,
      name: r.name,
      description: r.description ?? null,
      previewUrl: websiteAssetUrl(r.preview_image_path),
      base: (r.base ?? {}) as SitePreset,
      isPremium: !!r.is_premium,
      price: r.price ?? null,
    }));
  } catch {
    return presetThemes();
  }
}

/** One page template carried by a theme (seeds website_pages on apply). */
export type ThemePageTemplate = {
  kind: string;
  slug: string;
  title: string;
  nav_label: string;
  nav_order: number;
  show_in_nav: boolean;
  sections: unknown[];
};

export type ThemeBundle = {
  slug: string;
  base: SitePreset;
  pageTemplates: ThemePageTemplate[];
};

/** Load a catalogue theme (by uuid) with its base + page templates — for the
 * apply-theme flow. Returns null if not found / catalogue unavailable. */
export async function getThemeBundle(
  themeId: string,
): Promise<ThemeBundle | null> {
  try {
    const sb = createAdminClient() as unknown as SupabaseClient;
    const { data, error } = await sb
      .from("site_themes")
      .select("slug, base, page_templates")
      .eq("id", themeId)
      .eq("is_active", true)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as {
      slug: string;
      base: SitePreset;
      page_templates: ThemePageTemplate[] | null;
    } | null;
    if (error || !row) return null;
    return {
      slug: row.slug,
      base: row.base,
      pageTemplates: Array.isArray(row.page_templates)
        ? row.page_templates
        : [],
    };
  } catch {
    return null;
  }
}

/**
 * Load the default theme (is_default = true) with its base + page templates.
 * Used when creating a new website to apply the default theme automatically.
 * Falls back to the hardcoded "warm" preset if the DB is unavailable.
 */
export async function loadDefaultTheme(): Promise<ThemeBundle | null> {
  try {
    const sb = createAdminClient() as unknown as SupabaseClient;
    const { data, error } = await sb
      .from("site_themes")
      .select("slug, base, page_templates")
      .eq("is_default", true)
      .eq("is_active", true)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as {
      slug: string;
      base: SitePreset;
      page_templates: ThemePageTemplate[] | null;
    } | null;
    if (error || !row) return null;
    return {
      slug: row.slug,
      base: row.base,
      pageTemplates: Array.isArray(row.page_templates)
        ? row.page_templates
        : [],
    };
  } catch {
    return null;
  }
}

/**
 * Resolve a theme's visual base by slug — the authoritative source for what gets
 * stored on save (so we never trust a client-sent base). Falls back to the
 * built-in preset of the same slug when the catalogue is unavailable.
 */
export async function resolveThemeBase(slug: string): Promise<SitePreset> {
  try {
    const sb = createAdminClient() as unknown as SupabaseClient;
    const { data, error } = await sb
      .from("site_themes")
      .select("base")
      .eq("slug", slug)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as { base?: SitePreset } | null;
    if (!error && row?.base?.palette) return row.base;
  } catch {
    // fall through to preset fallback
  }
  if (slug in SITE_PRESETS) {
    return SITE_PRESETS[slug as keyof typeof SITE_PRESETS];
  }
  return SITE_PRESETS.warm;
}
