import "server-only";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import { websiteAssetUrl } from "@/lib/website/assets";

import { LAUNCH_THEME_SLUGS } from "@/lib/frontendFlags";

import { SITE_PRESETS, DEFAULT_PRESET, type SitePreset } from "./themes";

/**
 * Restrict a loaded catalogue to the launch allowlist (Royal only, for now — see
 * frontendFlags.LAUNCH_THEME_SLUGS). Keeps the catalogue's own ordering. An empty
 * allowlist disables the gate (returns the list unchanged). If the filter removes
 * everything (e.g. no Royal row in the catalogue) the caller falls back to the
 * preset themes, which are themselves gated to the same allowlist.
 */
function gateToLaunchThemes(themes: ThemeOption[]): ThemeOption[] {
  if (LAUNCH_THEME_SLUGS.length === 0) return themes;
  return themes.filter((t) => LAUNCH_THEME_SLUGS.includes(t.slug));
}

/**
 * A cookieless Supabase client for reading the PUBLIC theme catalogue.
 *
 * `site_themes` has a public read RLS policy (`select using (is_active and
 * deleted_at is null)`), so the catalogue can be read with the anon key — no
 * service role needed. Prefer the service-role key when present (bypasses RLS,
 * e.g. to resolve a base by slug regardless of is_active), but fall back to the
 * always-present anon key. This is what stops the picker silently collapsing to
 * a single preset when SUPABASE_SERVICE_ROLE_KEY isn't wired into a given
 * deployment environment (the previous `createAdminClient()` THREW in that case,
 * and every caller's try/catch degraded to the one-theme fallback).
 */
function themesReadClient(): SupabaseClient | null {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) return null;
  return createClient(url, key, {
    auth: { autoRefreshToken: false, persistSession: false },
    // Read the catalogue fresh every request. Supabase-js reads through `fetch`,
    // which the Next.js/Vercel Data Cache would otherwise persist — including a
    // stale empty result from before the anon grant / service key was in place,
    // which no redeploy would clear. `no-store` keeps the picker always current.
    global: {
      fetch: (input: RequestInfo | URL, init?: RequestInit) =>
        fetch(input, { ...init, cache: "no-store" }),
    },
  });
}

/** One selectable theme for the Brand Studio gallery / preset cards. */
export type ThemeOption = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  previewUrl: string | null;
  base: SitePreset;
  isPremium: boolean;
  price: number | null;
};

type ThemeRow = {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  preview_image_path: string | null;
  base: SitePreset;
  is_premium: boolean | null;
  price: number | null;
};

/** Built-in presets as a safety fallback when the site_themes catalogue is
 * empty/unavailable. Offers the launch allowlist (Royal only, for now — see
 * frontendFlags.LAUNCH_THEME_SLUGS) built from the in-code presets, so the host
 * still gets the launch theme even if the DB read fails. Falls back to the
 * default preset when the allowlist is empty or names no known preset. */
function presetThemes(): ThemeOption[] {
  const toOption = (slug: string): ThemeOption | null => {
    const preset = SITE_PRESETS[slug as keyof typeof SITE_PRESETS];
    if (!preset) return null;
    return {
      id: `preset:${slug}`,
      slug,
      name: preset.label,
      description: null,
      previewUrl: null,
      base: preset,
      isPremium: false,
      price: null,
    };
  };
  const gated = LAUNCH_THEME_SLUGS.map(toOption).filter(
    (o): o is ThemeOption => o !== null,
  );
  if (gated.length > 0) return gated;
  return [toOption(DEFAULT_PRESET)].filter((o): o is ThemeOption => o !== null);
}

/**
 * Load the active theme catalogue (site_themes), ordered. Falls back to the
 * built-in presets when the table doesn't exist yet, is empty, or errors — so
 * the studio works whether or not the migration has been applied. Uses the
 * admin client (catalogue is platform-managed, read here only).
 *
 * NOTE: queried through an untyped client cast because `site_themes` isn't in
 * the generated DB types in this lane (types are regenerated by the
 * consolidation lane after the migration is applied).
 */
export async function loadActiveThemes(
  sessionClient?: SupabaseClient,
): Promise<ThemeOption[]> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const noStore = (input: RequestInfo | URL, init?: RequestInit) =>
    fetch(input, { ...init, cache: "no-store" });
  const mk = (key?: string): SupabaseClient | null =>
    url && key
      ? createClient(url, key, {
          auth: { autoRefreshToken: false, persistSession: false },
          global: { fetch: noStore },
        })
      : null;

  // Prefer the caller's AUTHENTICATED session client: site_themes' admin RLS
  // policy calls is_super_admin(), which the anon role can be denied EXECUTE on
  // (that grant has proven flaky — a main-branch migration reset it and the
  // picker reverted to one preset), and a wrong/rejected service-role key fails
  // too. A logged-in user's client evaluates the policy fine, so it reads the
  // catalogue reliably. Fall back to fresh anon / service clients otherwise.
  const attempts: Array<{ label: string; sb: SupabaseClient | null }> = [
    { label: "session", sb: sessionClient ?? null },
    { label: "anon", sb: mk(process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) },
    { label: "service", sb: mk(process.env.SUPABASE_SERVICE_ROLE_KEY) },
  ];

  for (const { label, sb } of attempts) {
    if (!sb) continue;
    try {
      const { data, error } = await sb
        .from("site_themes")
        .select(
          "id, slug, name, description, preview_image_path, base, is_premium, price",
        )
        .eq("is_active", true)
        .is("deleted_at", null)
        .order("sort_order", { ascending: true });

      const rows = (data ?? []) as ThemeRow[];
      if (error) {
        console.warn(
          `[themes-load] ${label} key error: ${error.code ?? ""} ${error.message}`,
        );
        continue;
      }
      if (rows.length === 0) {
        console.warn(`[themes-load] ${label} key returned 0 rows`);
        continue;
      }
      console.info(`[themes-load] ${label} key → ${rows.length} themes`);
      const mapped: ThemeOption[] = rows.map((r) => ({
        id: r.id,
        slug: r.slug,
        name: r.name,
        description: r.description ?? null,
        previewUrl: websiteAssetUrl(r.preview_image_path),
        base: (r.base ?? {}) as SitePreset,
        isPremium: !!r.is_premium,
        price: r.price ?? null,
      }));
      // Launch gate: offer only the allowlisted theme(s) to hosts (Royal only,
      // for now). If the catalogue has no allowlisted row, fall through to the
      // preset fallback (which is gated the same way) rather than returning [].
      const gated = gateToLaunchThemes(mapped);
      if (gated.length === 0) {
        console.warn(
          `[themes-load] ${label} key returned ${mapped.length} themes but none matched the launch allowlist`,
        );
        continue;
      }
      return gated;
    } catch (e) {
      console.warn(
        `[themes-load] ${label} key threw: ${(e as Error)?.message ?? e}`,
      );
    }
  }

  console.warn("[themes-load] all attempts empty/failed → preset fallback");
  return presetThemes();
}

/** One page template carried by a theme (seeds website_pages on apply). */
export type ThemePageTemplate = {
  kind: string;
  slug: string;
  title: string;
  nav_label: string;
  nav_order: number;
  show_in_nav: boolean;
  sections: unknown[];
};

export type ThemeBundle = {
  slug: string;
  base: SitePreset;
  pageTemplates: ThemePageTemplate[];
};

/** Load a catalogue theme (by uuid) with its base + page templates — for the
 * apply-theme flow. Returns null if not found / catalogue unavailable. */
export async function getThemeBundle(
  themeId: string,
): Promise<ThemeBundle | null> {
  try {
    const sb = themesReadClient();
    if (!sb) return null;
    const { data, error } = await sb
      .from("site_themes")
      .select("slug, base, page_templates")
      .eq("id", themeId)
      .eq("is_active", true)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as {
      slug: string;
      base: SitePreset;
      page_templates: ThemePageTemplate[] | null;
    } | null;
    if (error || !row) return null;
    return {
      slug: row.slug,
      base: row.base,
      pageTemplates: Array.isArray(row.page_templates)
        ? row.page_templates
        : [],
    };
  } catch {
    return null;
  }
}

/**
 * Load the default theme (is_default = true) with its base + page templates.
 * Used when creating a new website to apply the default theme automatically.
 * Falls back to the hardcoded "warm" preset if the DB is unavailable.
 */
export async function loadDefaultTheme(): Promise<ThemeBundle | null> {
  try {
    const sb = themesReadClient();
    if (!sb) return null;
    const { data, error } = await sb
      .from("site_themes")
      .select("slug, base, page_templates")
      .eq("is_default", true)
      .eq("is_active", true)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as {
      slug: string;
      base: SitePreset;
      page_templates: ThemePageTemplate[] | null;
    } | null;
    if (error || !row) return null;
    return {
      slug: row.slug,
      base: row.base,
      pageTemplates: Array.isArray(row.page_templates)
        ? row.page_templates
        : [],
    };
  } catch {
    return null;
  }
}

/**
 * Resolve a theme's designed page templates by slug — the demo composition the
 * theme ships (home/about/rooms/contact/blog/...). Used by the theme-gallery
 * full-site PREVIEW so "preview" shows the theme's actual design, not the host's
 * own pages tinted with the theme. Returns [] if the catalogue is unavailable.
 */
export async function resolveThemePageTemplates(
  slug: string,
): Promise<ThemePageTemplate[]> {
  try {
    const sb = themesReadClient();
    if (!sb) return [];
    const { data, error } = await sb
      .from("site_themes")
      .select("page_templates")
      .eq("slug", slug)
      .is("deleted_at", null)
      .maybeSingle();
    const row = data as { page_templates?: ThemePageTemplate[] | null } | null;
    if (!error && Array.isArray(row?.page_templates)) return row.page_templates;
  } catch {
    // fall through
  }
  return [];
}

/**
 * Resolve a theme's visual base by slug — the authoritative source for what gets
 * stored on save (so we never trust a client-sent base). Falls back to the
 * built-in preset of the same slug when the catalogue is unavailable.
 */
export async function resolveThemeBase(slug: string): Promise<SitePreset> {
  try {
    const sb = themesReadClient();
    if (sb) {
      const { data, error } = await sb
        .from("site_themes")
        .select("base")
        .eq("slug", slug)
        .is("deleted_at", null)
        .maybeSingle();
      const row = data as { base?: SitePreset } | null;
      if (!error && row?.base?.palette) return row.base;
    }
  } catch {
    // fall through to preset fallback
  }
  if (slug in SITE_PRESETS) {
    return SITE_PRESETS[slug as keyof typeof SITE_PRESETS];
  }
  return SITE_PRESETS.warm;
}
