"use server";

import { redirect } from "next/navigation";

import { createServerClient } from "@/lib/supabase/server";

import { newListingSchema, type NewListingInput } from "./schemas";

export type CreateListingResult = { ok: true } | { ok: false; error: string };

export async function createListingAction(
  input: NewListingInput,
): Promise<CreateListingResult> {
  const parsed = newListingSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: "Please check the form and try again." };
  }
  const d = parsed.data;

  const supabase = createServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { ok: false, error: "Sign in to add a listing." };
  }

  // Need the host id to attribute the listing to.
  const { data: host } = await supabase
    .from("hosts")
    .select("id")
    .eq("user_id", user.id)
    .maybeSingle();
  if (!host) {
    return {
      ok: false,
      error: "Finish your host profile setup first.",
    };
  }

  // host_manage_own_listings RLS lets the user-bound client insert.
  const { data: listing, error } = await supabase
    .from("properties")
    .insert({
      host_id: host.id,
      listing_type: "accommodation",
      category_id: d.category_id,
      accommodation_type: d.accommodation_type ?? null,
      name: d.name,
      // is_published defaults to false; slug auto-generated by trigger.
    })
    .select("id")
    .single();
  if (error || !listing) {
    return { ok: false, error: "Could not create the listing. Try again." };
  }

  redirect(`/dashboard/listings/${listing.id}/edit`);
}
