import "server-only";

import type { createServerClient } from "@/lib/supabase/server";

// Reads the IMMUTABLE policy_snapshots frozen onto a booking at checkout — the
// "as booked" record. NEVER reads the live listing/policies, so later host edits
// don't change what a guest agreed to. Shared by the host booking detail and the
// guest trip view (G6). RLS lets both participants read their own snapshots, so
// either page's server client works.

type SupabaseServer = ReturnType<typeof createServerClient>;

export type CancellationRule = {
  daysBefore: number;
  refundPercent: number;
  label: string | null;
};

export type PoliciesAsBooked = {
  hasAny: boolean;
  cancellation: {
    name: string;
    summary: string | null;
    isNonRefundable: boolean;
    rules: CancellationRule[];
  } | null;
  checkInOut: {
    name: string;
    summary: string | null;
    checkInTime: string | null;
    checkOutTime: string | null;
    checkInMethod: string | null;
  } | null;
  houseRules: {
    name: string;
    summary: string | null;
    body: string | null;
  } | null;
  bookingTerms: {
    name: string;
    summary: string | null;
    body: string | null;
  } | null;
  acceptedTermsVersion: number | null;
  acceptedPrivacyVersion: number | null;
  acknowledgedAt: string | null;
};

type Row = { policy_type: string; snapshot_data: Record<string, unknown> };

function str(v: unknown): string | null {
  return typeof v === "string" && v.trim().length > 0 ? v : null;
}
// policy_content.body_plain is generated by stripping HTML tags but leaves HTML
// entities (e.g. "&amp;"), so decode the common ones for display.
function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}
function timeHHMM(v: unknown): string | null {
  const s = str(v);
  return s ? s.slice(0, 5) : null;
}

export async function loadPoliciesAsBooked(
  supabase: SupabaseServer,
  args: {
    bookingId: string;
    acceptedTermsVersion: number | null;
    acceptedPrivacyVersion: number | null;
    acknowledgedAt: string | null;
  },
): Promise<PoliciesAsBooked> {
  const { data } = await supabase
    .from("policy_snapshots")
    .select("policy_type, snapshot_data")
    .eq("booking_id", args.bookingId);

  const byType = new Map<string, Record<string, unknown>>();
  for (const r of (data ?? []) as Row[]) {
    byType.set(r.policy_type, r.snapshot_data ?? {});
  }

  const cx = byType.get("cancellation");
  const cancellation = cx
    ? {
        name: str(cx.name) ?? "Cancellation policy",
        summary: str(cx.summary),
        isNonRefundable: cx.is_non_refundable === true,
        rules: Array.isArray(cx.rules)
          ? (cx.rules as Record<string, unknown>[])
              .map((r) => ({
                daysBefore: Number(r.days_before ?? 0),
                refundPercent: Number(r.refund_percent ?? 0),
                label: str(r.label),
              }))
              .sort((a, b) => b.daysBefore - a.daysBefore)
          : [],
      }
    : null;

  const ci = byType.get("check_in_out");
  const checkInOut = ci
    ? {
        name: str(ci.name) ?? "Check-in & out",
        summary: str(ci.summary),
        checkInTime: timeHHMM(ci.check_in_time),
        checkOutTime: timeHHMM(ci.check_out_time),
        checkInMethod: str(ci.check_in_method),
      }
    : null;

  const contentBody = (data: Record<string, unknown>): string | null => {
    const content = (data.content ?? {}) as Record<string, unknown>;
    const raw = str(content.body_plain) ?? str(content.body_html);
    return raw ? decodeEntities(raw) : null;
  };

  const hr = byType.get("house_rules");
  const houseRules = hr
    ? {
        name: str(hr.name) ?? "House rules",
        summary: str(hr.summary),
        body: contentBody(hr),
      }
    : null;

  const bt = byType.get("booking_terms");
  const bookingTerms = bt
    ? {
        name: str(bt.name) ?? "Booking terms & conditions",
        summary: str(bt.summary),
        body: contentBody(bt),
      }
    : null;

  return {
    hasAny: Boolean(cancellation || checkInOut || houseRules || bookingTerms),
    cancellation,
    checkInOut,
    houseRules,
    bookingTerms,
    acceptedTermsVersion: args.acceptedTermsVersion,
    acceptedPrivacyVersion: args.acceptedPrivacyVersion,
    acknowledgedAt: args.acknowledgedAt,
  };
}
