import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import { createAdminClient } from "@/lib/supabase/admin";

// Design restore points (Phase 2.5). A snapshot captures the live design (theme
// + brand) + all pages so a host can roll back after switching themes. Accessed
// through an untyped admin client because `website_restore_points` isn't in the
// generated DB types in this lane (regenerated by the consolidation lane).
//
// Owner checks happen in the calling server actions; the admin client is used
// here for the reads/writes.

const KEEP_AUTO = 20; // prune auto_switch points beyond the newest N per site

export type SnapshotPage = {
  kind: string;
  slug: string;
  title: string | null;
  nav_label: string | null;
  nav_order: number;
  show_in_nav: boolean;
  sections: unknown;
};

export type DesignSnapshot = {
  theme: Record<string, unknown>;
  brand: Record<string, unknown>;
  pages: SnapshotPage[];
};

export type RestorePointMeta = {
  id: string;
  label: string | null;
  themeSlug: string | null;
  kind: string;
  createdAt: string;
};

function admin(): SupabaseClient {
  return createAdminClient() as unknown as SupabaseClient;
}

/** Snapshot the live design (theme + brand + all pages) into a restore point. */
export async function captureRestorePoint(
  websiteId: string,
  label: string | null,
  kind: "manual" | "auto_switch",
): Promise<void> {
  const sb = admin();

  const { data: siteRaw } = await sb
    .from("host_websites")
    .select("theme, brand")
    .eq("id", websiteId)
    .maybeSingle();
  const site = siteRaw as {
    theme?: Record<string, unknown>;
    brand?: Record<string, unknown>;
  } | null;

  const { data: pagesRaw } = await sb
    .from("website_pages")
    .select(
      "kind, slug, title, nav_label, nav_order, show_in_nav, draft_sections",
    )
    .eq("website_id", websiteId)
    .order("nav_order", { ascending: true });
  const pageRows = (pagesRaw ?? []) as Array<{
    kind: string;
    slug: string;
    title: string | null;
    nav_label: string | null;
    nav_order: number;
    show_in_nav: boolean;
    draft_sections: unknown;
  }>;

  const theme = site?.theme ?? {};
  const snapshot: DesignSnapshot = {
    theme,
    brand: site?.brand ?? {},
    pages: pageRows.map((p) => ({
      kind: p.kind,
      slug: p.slug,
      title: p.title,
      nav_label: p.nav_label,
      nav_order: p.nav_order,
      show_in_nav: p.show_in_nav,
      sections: p.draft_sections ?? [],
    })),
  };
  const themeSlug =
    typeof (theme as { preset?: unknown }).preset === "string"
      ? (theme as { preset: string }).preset
      : null;

  await sb.from("website_restore_points").insert({
    website_id: websiteId,
    label,
    theme_slug: themeSlug,
    snapshot,
    kind,
  });

  if (kind === "auto_switch") {
    const { data: oldRaw } = await sb
      .from("website_restore_points")
      .select("id")
      .eq("website_id", websiteId)
      .eq("kind", "auto_switch")
      .order("created_at", { ascending: false })
      .range(KEEP_AUTO, KEEP_AUTO + 500);
    const ids = ((oldRaw ?? []) as Array<{ id: string }>).map((r) => r.id);
    if (ids.length) {
      await sb.from("website_restore_points").delete().in("id", ids);
    }
  }
}

/** Write a snapshot back as the live site: replace pages + reset theme/brand. */
export async function restoreSnapshotToSite(
  websiteId: string,
  snapshot: DesignSnapshot,
): Promise<boolean> {
  const sb = admin();

  await sb.from("website_pages").delete().eq("website_id", websiteId);
  const { error: pErr } = await sb.from("website_pages").insert(
    snapshot.pages.map((p) => ({
      website_id: websiteId,
      kind: p.kind,
      slug: p.slug,
      title: p.title,
      nav_label: p.nav_label,
      nav_order: p.nav_order,
      show_in_nav: p.show_in_nav,
      draft_sections: p.sections ?? [],
      published_sections: [],
    })),
  );
  if (pErr) return false;

  const { error: tErr } = await sb
    .from("host_websites")
    .update({ theme: snapshot.theme, brand: snapshot.brand })
    .eq("id", websiteId);
  return !tErr;
}

/** List a site's restore points (newest first). */
export async function listRestorePoints(
  websiteId: string,
): Promise<RestorePointMeta[]> {
  const { data } = await admin()
    .from("website_restore_points")
    .select("id, label, theme_slug, kind, created_at")
    .eq("website_id", websiteId)
    .order("created_at", { ascending: false })
    .limit(60);
  const rows = (data ?? []) as Array<{
    id: string;
    label: string | null;
    theme_slug: string | null;
    kind: string;
    created_at: string;
  }>;
  return rows.map((r) => ({
    id: r.id,
    label: r.label,
    themeSlug: r.theme_slug,
    kind: r.kind,
    createdAt: r.created_at,
  }));
}

/** Fetch one restore point (with its website id, for an ownership check). */
export async function getRestorePoint(
  id: string,
): Promise<{ websiteId: string; snapshot: DesignSnapshot } | null> {
  const { data } = await admin()
    .from("website_restore_points")
    .select("website_id, snapshot")
    .eq("id", id)
    .maybeSingle();
  const row = data as {
    website_id: string;
    snapshot: DesignSnapshot;
  } | null;
  if (!row) return null;
  return { websiteId: row.website_id, snapshot: row.snapshot };
}

export async function deleteRestorePoint(id: string): Promise<void> {
  await admin().from("website_restore_points").delete().eq("id", id);
}

/** The host's latest auto-captured snapshot for a theme slug — restored when
 * they return to a previously-used theme (brings back their customised work). */
export async function latestAutoForTheme(
  websiteId: string,
  slug: string,
): Promise<DesignSnapshot | null> {
  const { data } = await admin()
    .from("website_restore_points")
    .select("snapshot")
    .eq("website_id", websiteId)
    .eq("kind", "auto_switch")
    .eq("theme_slug", slug)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  const row = data as { snapshot: DesignSnapshot } | null;
  return row?.snapshot ?? null;
}

/** The catalogue's default theme id (the guaranteed-working reset target).
 * Falls back to the Classic preset when the catalogue is unavailable. */
export async function resolveDefaultThemeId(): Promise<string> {
  try {
    const { data } = await admin()
      .from("site_themes")
      .select("id")
      .eq("is_default", true)
      .eq("is_active", true)
      .is("deleted_at", null)
      .limit(1)
      .maybeSingle();
    const row = data as { id: string } | null;
    if (row?.id) return row.id;
  } catch {
    // fall through
  }
  return "preset:classic";
}
